apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis-exporter-podmonitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: redis-exporter
  podMetricsEndpoints:
    - port: metrics
      interval: 5s