global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:8080"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:2112"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]