apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migrate
  namespace: app
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: sgawalsh/postgres-notifications-migrate:latest
          command: ["node", "migrations/cli.js"]
          envFrom:
            - configMapRef:
                name: api-config
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret