apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poller
  template:
    metadata:
      labels:
        app: poller
    spec:
      containers:
        - name: poller
          image: sgawalsh/postgres-notifications-worker:latest
          env:
            - name: ROLE
              value: poller
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: poller-config
            - secretRef:
                name: postgres-secret
