name: Container Security Scan

on:
  push:
  pull_request:

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build API image
        run: docker build --target=runtime -t job-processor-api ./api

      - name: Scan API image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: job-processor-api
          severity: HIGH,CRITICAL
          exit-code: 1

  check-nginx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build nginx image
        run: docker build -f ./infra/nginx/Dockerfile.prod -t job-processor-nginx .

      - name: Scan nginx image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: job-processor-nginx
          severity: HIGH,CRITICAL
          exit-code: 1

  check-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build worker image
        run: docker build -t job-processor-worker ./worker

      - name: Scan worker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: job-processor-worker
          severity: HIGH,CRITICAL
          exit-code: 1